<script lang="ts">
	// @ts-nocheck
	import "../app.css";
	import logo from "../assets/logo.svg";
	import title from "../assets/title.svg";
	import language from "../assets/language.svg";
	import cx from "clsx";
	import { slide, fly } from "svelte/transition";
	import menu from "../assets/menu.svg";
	import { onDestroy, onMount } from "svelte";
	import { goto } from "$app/navigation";
	import { resolve } from "$app/paths";
	import { page } from "$app/stores";
	import { userInfo } from "../stores/userInfo";
	import Groups from "../icons/Groups.svelte";
	import { LANGUAGES } from "../config/const";
	import { localeLanguage } from "../stores/localeLanguage";
	import { t } from "../utils/t";
	import { i18nConstants } from "../config/i18n";
	import SideBar from "../components/history/SideBar.svelte";
	import { globalLoading } from "../stores/globalLoading";
	import { editMode } from "../stores/editMode";
	import { initEasterEgg } from "../utils/easterEgg";
	import { initializeApp } from "../stores/appInit";
	import { Message } from "../utils/Message";

	let { children } = $props();

	let showAvatarDetail = $state(false);
	let showLanguageSelector = $state(false);
	let home: HTMLDivElement = $state();
	let user: HTMLDivElement = $state();
	let tabLine: HTMLDivElement = $state();
	let hideTopBar = $state(false);
	let lastScrollTop = 0;
	let hide = $state(true);
	let cleanupEasterEgg: () => void;

	// ly: generated by gpt3.5 :)
	const handleScroll = () => {
		const doc = document.documentElement;
		const scrollTop = (window.pageYOffset || doc.scrollTop) - (doc.clientTop || 0);
		if (scrollTop > lastScrollTop) {
			hideTopBar = true;
		} else {
			hideTopBar = false;
		}
		lastScrollTop = scrollTop <= 0 ? 0 : scrollTop;
	};
	const i18nKeys = Object.keys(i18nConstants) as (keyof typeof i18nConstants)[];

	initializeApp();

	const updateTabLine = (pathname = $page.url.pathname) => {
		if (tabLine && user && home) {
			Promise.resolve().then(() => {
				const isUserRoute = pathname === "/user";
				tabLine.style.width = `${isUserRoute ? user.clientWidth : home.clientWidth}px`;
				tabLine.style.transform = isUserRoute
					? `translateX(${home.clientWidth + 32}px)`
					: "translateX(0px)";
			});
		}
	};

	const handleRouterClick = async (path: string) => {
		if ($editMode) {
			Message.warning("请先退出编辑模式，以防数据丢失");
			return;
		}

		await goto(resolve(path, {}));
	};

	$effect(() => {
		const pathname = $page.url.pathname;
		const language = $localeLanguage;
		updateTabLine(pathname);
		void language;
	});

	onMount(() => {
		window.addEventListener("scroll", handleScroll, false);
		cleanupEasterEgg = initEasterEgg();
		updateTabLine();
	});

	onDestroy(() => {
		cleanupEasterEgg?.();
		window.removeEventListener("scroll", handleScroll);
	});
</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class="h-full min-h-screen overflow-scroll bg-[rgba(0,0,0,0.04)] sm:pt-[6rem]">
	<div
		class={cx([
			"left-0 top-0 z-20 h-[5rem] w-full bg-[rgba(49,84,174,0.58)] px-[4rem] py-[0.5rem] transition-all duration-700 max-lg:px-[3rem] max-md:px-[1rem] max-sm:flex max-sm:bg-[#315ED0] sm:fixed sm:grid sm:grid-cols-3",
			hideTopBar ? "translate-y-[-5rem]" : "translate-y-0"
		])}
	>
		<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
		<img src={menu} alt="menu" onclick={() => (hide = false)} class="self-center sm:hidden" />
		<a class="flex-shrink-0 self-end max-sm:hidden" href="https://hustunique.com" target="_blank">
			<div class="flex items-center gap-[0.5rem]">
				<img draggable={false} src={logo} alt="UniqueStudio" />
				<p class="mb-[0.5rem] text-lg text-white">{$t("header.team")}</p>
			</div>
		</a>
		<div class="flex w-full justify-center sm:hidden">
			<img src={title} alt="联创招新" class="mx-auto h-[22px] flex-shrink-0 self-center" />
		</div>
		<div
			class="relative flex flex-shrink-0 gap-[2rem] self-center justify-self-center text-white max-sm:hidden"
		>
			<div bind:this={home} class="cursor-pointer" onclick={() => handleRouterClick("/")}>
				{$t("header.applications")}
			</div>
			<div bind:this={user} class="cursor-pointer" onclick={() => handleRouterClick("/user")}>
				{$t("header.info")}
			</div>
			<div
				bind:this={tabLine}
				class={cx(["absolute bottom-[-0.5rem] h-[3px] rounded-full bg-white transition-all"])}
			></div>
		</div>
		{#if $userInfo}
			<div
				class="relative ml-auto flex flex-shrink-0 select-none items-center self-center sm:mr-[2rem] sm:gap-[24px]"
			>
				<div>
					<!-- svelte-ignore a11y_no_noninteractive_element_interactions -->
					<img
						onclick={() => (showLanguageSelector = !showLanguageSelector)}
						alt="language"
						class="h-[24px] w-[24px] cursor-pointer max-sm:hidden"
						src={language}
					/>
					{#if showLanguageSelector}
						<div
							transition:slide
							class="absolute right-[64px] top-[48px] z-[999] w-[149px] rounded-[6px] bg-white py-[6px]"
						>
							{#each i18nKeys as key (key)}
								<button
									onclick={() => {
										showLanguageSelector = false;
										localeLanguage.updateLanguage(key);
									}}
									class="h-[46px] w-full text-center leading-[46px] hover:bg-gray-150 max-md:h-[32px] max-md:leading-[32px]"
									>{LANGUAGES[key]}</button
								>
							{/each}
						</div>
					{/if}
				</div>
				<div class="relative">
					<div
						onclick={() => (showAvatarDetail = !showAvatarDetail)}
						class=" h-[40px] w-[40px] cursor-pointer rounded-full bg-white text-center leading-[40px] text-text-3 max-sm:h-[32px] max-sm:w-[32px] max-sm:text-[12px] max-sm:leading-[32px]"
					>
						{$userInfo.name[0]}
					</div>
					{#if showAvatarDetail}
						<div
							transition:slide
							class="absolute right-0 top-[48px] w-[149px] rounded-[6px] bg-white py-[6px]"
						>
							<button
								onclick={() => (window.location.href = "https://sso2024.hustunique.com/")}
								class="h-[46px] w-full text-center leading-[46px] hover:bg-gray-150 max-md:h-[32px] max-md:leading-[32px]"
								>{$t("header.accountManagement")}</button
							>
							<button
								onclick={() =>
									(window.location.href =
										"https://sso2024.hustunique.com/login?logout=true&from=join2024.hustunique.com")}
								class="h-[46px] w-full text-center leading-[46px] text-red-warning hover:bg-gray-150 max-md:h-[32px] max-md:leading-[32px]"
								>{$t("header.logout")}</button
							>
						</div>
					{/if}
				</div>
			</div>
		{/if}
	</div>
	<div
		class="fixed left-0 top-0 -z-10 h-[15rem] w-full overflow-hidden bg-[rgba(53,100,221,1)] max-sm:invisible"
	>
		<Groups />
	</div>
	{@render children()}
</div>

{#if $globalLoading}
	<div class="fixed inset-0 z-[100] flex items-center justify-center bg-white/20">
		<div
			transition:fly={{ y: 20, duration: 300 }}
			class="shadow-2xl flex flex-col items-center gap-4 rounded-xl border border-gray-100 bg-white p-8"
		>
			<div
				class="h-10 w-10 animate-spin rounded-full border-4 border-blue-400 border-t-transparent"
			></div>
			<p class="text-gray-700 text-base font-medium">
				{$t("header.loading")}
			</p>
		</div>
	</div>
{/if}

<div class="sm:hidden">
	<SideBar {hide} onHide={() => (hide = true)} />
</div>

<style>
	@font-face {
		font-family: "PingFang";
		src: url("/PingFangSC-Regular.woff2");
	}

	* {
		font-family: "PingFang", sans-serif;
	}
</style>
